import React, { useEffect, useState, useRef } from "react";
import { useDispatch, useSelector } from "react-redux";
import { connect } from "./redux/blockchain/blockchainActions";
import { fetchData } from "./redux/data/dataActions";
import swal  from 'sweetalert';
import styled from "styled-components";

function App() {
  const comingSoon = () => {
	swal("CoolBeez NFT coming soon", "", "info");
  }

  return (
    <div>
		<nav className="navbar container-fluid wow fadeInDown">
			<a href="#">
				{/* <div className="navbar_logo float-left">CoolBeez</div> */}
			</a>
			<div className="float-right navbar_right">
				<button className="connect-button btn ml-2 d-inline-block no-display"><i className="fa-solid fa-network-wired"></i> CONNECT</button>
			</div>
		</nav>

		<section className="hero-section wow zoomIn">
			<img className="width-100 website-hero-back" src="./assets/images/new_banner.png"/>
			<img className="width-100 mobile-hero-back" src="./assets/images/new_banner_mobile.png"/>
		</section>

		<div className="main-container">
			<section className="about-section">
				<div className="col-12 text-center d-flex justify-content-center wow fadeInUp">
					<span className="section_title line-height-15">WELCOME TO THE COOLBEEZ</span>
				</div>
				<div className="row mx-0 px-0 pt-30">
					<div className="col-md-4 mt-md-0 px-5 mr-0 wow rollIn d-flex align-items-center justify-content-center">
						<div className="text-center">
							<img className="img-thumbnail character-gif" src="./assets/images/character.gif"/>
						</div>
					</div>
					<div className="col-md-8 d-flex px-5 align-items-center text-center welcome-text-block">
						<div className="pl-md-3">
							<div className="pt-md-3  wow fadeInUp">
								<span className="font_general line-height-15">
									Coolbeez is a unique Ethereum based Community Utility NFT featuring 6000 NFTs generated from hand drawn characters and 165 traits and is the first in a series of community collections from the https://www.mymetafoundation.org/. 
									As a holder of a CoolBeez NFT you will be part of the largest land-NFT owning community in the Metaverse. Proceeds from the sales of the collection are deposited in the Community Development Fund wallet which is used to purchase and develop community owned spaces in the metaverse. 
									The land and proceeds from the utility of the land is 100% owned by the community and held in the Community Development Fund wallet. 
									All holders of CoolBeez NFTs will benefit from the passive income generated by the land NFTs from day 1. Income will be deposited into the wallet that holds the CoolBeez NFT on a monthly basis. 
								</span>
							</div>
							<div className="text-center wow zoomInUp">
								<button 
									className="mint_button btn mt-5 "
									onClick={(e) => {
										e.preventDefault();
										comingSoon();
									}}
								>
									MINT
								</button>
							</div>
						</div>
					</div>
				</div>
			</section>
		
			<section className="join-discord">
				<div className="row mx-0">
					<div className="col-md-5 col-sm-12 text-center wow slideInLeft">
						<img className="discord-bee" src="./assets/images/discord_bee.png"/>
					</div>
					<div className="col-md-7 col-sm-12 text-block d-flex align-items-center text-center wow slideInRight">
						<div className="pl-md-3">
							<div className="join-discord-title rubik-font">
								JOIN OUR DISCORD
							</div>
							<div className="join-discord-content">
								Do you want to be on the whitelist? 
								Get all the latest information on the CoolBeez Discord server. Come on in!
							</div>
							<a href="https://discord.gg/awq7t3nt8u" target="_blank">
								<button className="join-button"><i className="fab fa-discord"></i> JOIN DISCORD</button>
							</a>
						</div>
					</div>
				</div>
			</section>

			<section className="slide-container">
				<div className="col-12 text-center d-flex justify-content-center wow fadeInUp">
					<div className="section_title line-height-15">CoolBeez NFT</div>
				</div>
				<div className="coolbeez-content text-center font_general line-height-18 pt-30 wow bounceIn">
					All metaverse real estate, utilities and subsequent revenues generated in the metaverse by the community real estate portfolio will be 100% owned by our NFT holders and held in the CDF. 
					All holders become virtual-landlords in the new virtual world with an equal share in the real estate portfolio based on the number of NFTs that you hold!
					The Community Development Fund will also be used to develop anything from game rooms, events halls and stores to VR meeting and private family rooms. 
				</div>
				<div className="swiper mySwiper wow fadeIn">
					<div className="swiper-wrapper">
						<div className="swiper-slide">
							<img className="slide_image img-thumbnail" src="./assets/images/Mascots V3 1.jpg" alt=""/>
						</div>
						<div className="swiper-slide">
							<img className="slide_image img-thumbnail" src="./assets/images/Mascots V3 2.jpg" alt=""/>
						</div>
						<div className="swiper-slide">
							<img className="slide_image img-thumbnail" src="./assets/images/Mascots V3 3.jpg" alt=""/>
						</div>
						<div className="swiper-slide">
							<img className="slide_image img-thumbnail" src="./assets/images/Mascots V3 4.jpg" alt=""/>
						</div>
						<div className="swiper-slide">
							<img className="slide_image img-thumbnail" src="./assets/images/Mascots V3 5.jpg" alt=""/>
						</div>
						<div className="swiper-slide">
							<img className="slide_image img-thumbnail" src="./assets/images/Mascots V3 6.jpg" alt=""/>
						</div>
						<div className="swiper-slide">
							<img className="slide_image img-thumbnail" src="./assets/images/Mascots V3 7.jpg" alt=""/>
						</div>
					</div>
					<div className="swiper-pagination"></div>
				</div>
			</section>

			<section className="game-section pt-30">
				<div className="col-12 text-center d-flex justify-content-center wow fadeInUp">
					<div className="section_title line-height-15">Where will we buy? <br/> We let the community decide!</div>
				</div>
				<div className="row mx-0 mt-5">
					<div className="col-md-4 col-sm-12 text-center wow fadeInLeft">
						<div className="game-title rubik-font">Sandbox</div>
						<img className="mt-3 img-thumbnail width-100 game-image" src="./assets/images/sandbox.png"></img>
					</div>
					<div className="col-md-4 col-sm-12 text-center wow fadeInLeft">
						<div className="game-title rubik-font">Decentraland</div>
						<img className="mt-3 img-thumbnail width-100 game-image" src="./assets/images/decentraland.png"></img>
					</div>
					<div className="col-md-4 col-sm-12 text-center wow fadeInLeft">
						<div className="game-title rubik-font width-100 game-image">Somniumspace</div>
						<img className="mt-3 img-thumbnail" src="./assets/images/somniumspace.png"></img>
					</div>
				</div>
			</section>

			<div className="col-12 text-center d-flex justify-content-center pt-30">
				<span className="section_title gtfcduyjdc wow fadeInUp">THE ROADMAP</span>
			</div>
			<div className="coolbeez-content text-center font_general line-height-18 wow bounceIn pt-30">
				Whilst the My Meta Foundation have an ambitious plan outlined to grow the community as quickly as possible, the whole purpose of this community is for you to decide the roadmap once the foundations have been laid. 
				There will be votes along the way for all NFT holders, but here is what we have so far:
			</div>
			<div className="row mx-0">
				<div className="col-md-7 col-sm-12">
					<section className="roadmap pb-5">
						<div className="roadmap_title_back"></div>
						<div className="top_one container-fluid mt-5 roadmap-padding">
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-2">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"> </span>
												<span className="top_title line-height-12">March (dates TBC)</span>
											</div>
											<div className="font_general line-height-12">
												CoolBeez Smart Contract deployed. <br/>
												CoolBeez Whitelist Presale. <br/>
												CoolBeez Public Sale.
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-2">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"></span>
												<span className="top_title line-height-12">April</span>
											</div>
											<div className="font_general line-height-12">
												Community voting round 1/22 – Metaverse land location vote.<br/>
												Community Meteverse land purchase from CoolBeez launch.<br/>
												Community voting round 2/22 – Metaverse land usage vote.
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-3">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"> </span>
												<span className="top_title line-height-12">May</span>
											</div>
											<div className="font_general line-height-12">
												Whitelisting and Discord opening for ‘Anti-Social Elephant Club ’ collection.<br/>
												Community voting round 3/22 – Community Development Fund usage for 2022 vote. 
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-2">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"> </span>
												<span className="top_title line-height-12">June</span>
											</div>
											<div className="font_general line-height-12">
												Anti-Social Elephant Club Smart Contract deployed.<br/>
												Anti-Social Elephant Club Whitelist Presale.<br/>
												Anti-Social Elephant Club Airdrop to existing CoolBeez holders.<br/>
												Anti-Social Elephant Club Public Sale.<br/>
												Develop new community voting platform.<br/>
												Develop Metaverse land usage decided in voting round 3.
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-2">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"> </span>
												<span className="top_title line-height-12">July</span>
											</div>
											<div className="font_general line-height-12">
												Whitelist and Discord opening for ‘Pretty But Deadly’ collection.<br/>
												Community voting round 4/22 – second Metaverse land location vote.<br/>
												Community Meteverse land purchase from Anti-Social Elephant Club launch.<br/>
												Community voting round 5/22 – Metaverse land usage vote.<br/>
												Pretty But Deadly Airdrop to existing community NFT holders.<br/>
												Community Meteverse Anti-Social Elephant Club land development.
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-2">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"> </span>
												<span className="top_title line-height-12">August</span>
											</div>
											<div className="font_general line-height-12">
												Pretty But Deadly Smart Contract deployed.<br/>
												Pretty But Deadly Whitelist Presale.<br/>
												Pretty But Deadly Airdrop to existing community NFT holders.<br/>
												Pretty But Deadly Public Sale.
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-2">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"> </span>
												<span className="top_title line-height-12">September</span>
											</div>
											<div className="font_general line-height-12">
												Ready 4th NFT collection launch as voted on by the community. 
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="row pb-3 mx-0 position-relative mx-0 wow fadeInUp">
								<div className="col-md-12">
									<div className="row rounded roadmap_round py-2">
										<div className="col-md-1 col-2 d-inline dot_data p-0">
											<span className="dot"></span>
										</div>
										<div className="col-md-11 col-10 d-inline mt-0">
											<div className="">
												<span className="top_title_num roadmap_font"> </span>
												<span className="top_title line-height-12">The Future</span>
											</div>
											<div className="font_general line-height-12">
												The future is your hands!
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
				</div>
				<div className="col-md-5 col-sm-12">
					<div className="roadmap_right_content">
						<div className="mb-5 font_general line-height-15 wow fadeInUp">
							•	Total Blockchain Transparency – Our commitment is to the community, and we want to ensure complete transparency in the process. Therefore, we have implemented fully auditable smart contracts to distribute funds to the Community Development Fund, Charity, and Passive Income wallets directly on a per sale basis. <br/>
						</div>
						<div className="mb-5 font_general line-height-15 wow fadeInUp">
							•	Members of the CoolBeez development team or the My Meta Foundation are NOT PERMITTED to own one of our own NFTs. This will ensure that voting represents the autonomous nature and true wishes of the community. <br/>
						</div>
						<div className="mb-5 font_general line-height-15 wow fadeInUp">
							•	You drive the future of the community through votes on a one vote per NFT basis. The voting process will be held on the blockchain to ensure transparency to all. <br/>
						</div>
						<div className="mb-5 font_general line-height-15 wow fadeInUp">
							•	How will passive income for all holders of the NFT? On a quarterly basis we will deploy a smart contract to the most cost-effective network, such as Matic which will distribute the total amount held in the Community’s Passive Income Wallet to all holders within the community on a per-NFT basis. This will minimize the high gas fees which would otherwise eat into your profits. <br/>
						</div>
						<div className="mb-5 font_general line-height-15 wow fadeInUp">
							•	We have created just 6000 NFTs to ensure that the passive income levels are as high as possible whilst also allowing the community to purchase land-NFTs that will retain their value and be highly rentable. <br/>
						</div>
						<div className="mb-5 font_general line-height-15 wow fadeInUp">
							•	As the prices of your NFT and the cost of land in the Metaverse increase so will your returns. <br/>
						</div>
						<div className="mb-5 font_general line-height-15 wow fadeInUp">
							•	The community decides on the future of the land-NFTs, all assets held with the Community Development Fund and how it is used. For example, if in the future the community receives an offer to sell the land NFT at a huge mark-up, the community can decide to sell and deposit the proceeds into the Passive Income Wallet for distribution to holders in the following quarter. 	
						</div>
					</div>
				</div>
			</div>
			

			<section className="section-qa">
				<div className="col-12 text-center d-flex justify-content-center">
					<span className="section_title gtfcduyjdc wow fadeInUp">FAQS</span>
				</div>
				<div className="content container-fluid mt-md-5 mt-4 footer-padding">
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">What is CoolBeez?</h1>
						</button>
						<div className="panel">
							<p>CoolBeez is a Community NFT collection with unique holder benefits and is part of the My Meta Foundation. </p>
						</div>
					</div>
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">When will the CoolBeez NFT collection be launched and minted?</h1>
						</button>
						<div className="panel">
							<p>The CoolBeez NFT collection is expected to be launched and minted by the end of March 2022. </p>
						</div>
					</div>
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">What is the expected floor price for CoolBeez? </h1>
						</button>
						<div className="panel">
							<p>The expected floor price of the CoolBeez NFT collection will be announced on our Discord server shortly. </p>
						</div>
					</div>
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">Where can I buy a CoolBeez NFT? </h1>
						</button>
						<div className="panel">
							<p>You can get hold of a CoolBeez NFT by visiting OpenSea or directly from this page by linking your wallet. CoolBeez NFT collection on OpenSea: https://opensea.io/collection/coolbeez </p>
						</div>
					</div>
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">When will the Whitelist be available? </h1>
						</button>
						<div className="panel">
							<p>The Whitelist for the CoolBeez NFT collection will be opened by mid-February 2022, but due to the increasing demand that we have already, we may bring this forward. 
								Places are limited but the first 100 members to join our discord will be guaranteed a place. 
								Places will also be available through giveaways and competitions hosted on Discord.</p>
						</div>
					</div>
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">What utility does the CoolBeez NFT have?  </h1>
						</button>
						<div className="panel">
							<p>CoolBeez NFT owners will own a share in the Community Development Fund and in the virtual metaverse real estate portfolio. Each NFT you hold allows you one vote to decide how the CDF is used to develop the metaverse land that the community owns. </p>
						</div>
					</div>
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">How will you grow the community after the CoolBeez collection is sold out? </h1>
						</button>
						<div className="panel">
							<p>The CoolBeez collection is part of the My Meta Foundation. The foundations road map is to release 6 NFT collections throughout 2022 and 2023. The next in the series is ‘Anti-Social Elephant Club’ with work on the project already underway. Holders of all future NFT collections will join the community and proceeds from the sales of the collections will be donated to the same Community Development Fund. As the community grows, so does the fund and the portfolio.</p>
						</div>
					</div>
					<div className="mt-2 accordion-container footer_round wow slideInRight">
						<button className="accordion py-0">
							<h1 className="footer-font">Why does the project support good causes and how will that affect the Community Development Fund?</h1>
						</button>
						<div className="panel">
							<p>We believe that the Future of Giving lays in the power of Web 3.0 and we want to create a bridge between our two worlds. The creators will donate a percentage of the foundation’s profits to good causes. The Community Development Fund will NOT be used for charitable donations unless the community decide to do so. </p>
						</div>
					</div>
				</div>
			</section>

			<section className="team-section">
				<div className="col-12 text-center d-flex justify-content-center wow fadeInUp">
					<div className="section_title line-height-15">MEET OUR TEAM</div>
				</div>
				<div className="row mx-0">
					<div className="col-lg-1 col-md-0"></div>
					<div className="col-lg-2 col-md-6 col-sm-12 text-center wow zoomInUp" data-wow-offset="150">
						<img className="team-image" src="./assets/images/Mascots V3 1.png"/>
						<div className="team-caption">
							Founder <br/>
							Dan Maguire 
						</div>
					</div>
					<div className="col-lg-2 col-md-6 col-sm-12 text-center wow zoomInUp" data-wow-offset="150">
						<img className="team-image" src="./assets/images/Mascots V3 2.png"/>
						<div className="team-caption">
							Co-Founder <br/>
							Bart Vonk 
						</div>
					</div>
					<div className="col-lg-0 col-md-3 col-sm-0 bingo-col"></div>
					<div className="col-lg-2 col-md-6 col-sm-12 text-center wow zoomInUp" data-wow-offset="150">
						<img className="team-image" src="./assets/images/Mascots V3 3.png"/>
						<div className="team-caption">
							Visionary <br/>
							Ella Maguire 
						</div>
					</div>
					<div className="col-lg-0 col-md-3 col-sm-0 bingo-col"></div>
					<div className="col-lg-2 col-md-6 col-sm-12 text-center wow zoomInUp" data-wow-offset="150">
						<img className="team-image" src="./assets/images/Mascots V3 4.png"/>
						<div className="team-caption">
							Dev <br/>
							Malin Zhang
						</div>
					</div>
					<div className="col-lg-2 col-md-6 col-sm-12 text-center wow zoomInUp" data-wow-offset="150">
						<img className="team-image" src="./assets/images/Mascots V3 5.png"/>
						<div className="team-caption">
							Artist <br/>
							Anon
						</div>
					</div>
					<div className="col-lg-1 col-md-0"></div>
				</div>
			</section>
			{/* <section className="social-links text-center">
				<a href="https://twitter.com/CoolBeezNFT" target="_blank">
					<i className="fab fa-twitter social-icon"></i>
				</a>
				<a href="https://www.facebook.com/coolbeeznft" target="_blank">
					<i className="fab fa-facebook social-icon"></i>
				</a>
				<a href="https://www.instagram.com/coolbeeznft/" target="_blank">
					<i className="fab fa-instagram social-icon"></i>
				</a>
				<a href="https://www.instagram.com/coolbeeznft/" target="_blank">
					<img className="opensea-image" src="./assets/images/opensea.png"/>
				</a>
				<a href=" https://www.mymetafoundation.org/" target="_blank">
					<i className="fa fa-link social-icon"></i>
				</a>
			</section> */}
		</div>
    </div>
  );
}

export default App;
